version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-pgadmin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pgadmin}
      POSTGRES_DB: ${POSTGRES_DB:-sandbox}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres_vol:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - postgres_net
  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-agent@pgadmin4.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-pgadmin4}
    volumes:
     - pgadmin-vol:/var/lib/pgadmin
    ports:
      - ${PGADMIN_LISTEN_PORT:-5050}:80
    depends_on:
      - postgres
    links:
      - "postgres:pgsql-server"
    networks:
     - postgres_net

networks:
  postgres_net:
    driver: bridge

volumes:
  postgres_vol:
    driver: local
  pgadmin-vol:
    driver: local